### PR TITLE
JENKINS-29605 trigger builds on pullrequest

### PR DESCRIPTION
**Pull request by lkokhreidze**

### CODE REVIEW

**Comment by lkokhreidze** [comment]
@fbelzunc Hello, would you mind to give any approximation when this PR will be reviewed?

**Comment by imod** [comment]
is the idea to replace this plugin? https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+pullrequest+builder+plugin

**Comment by fbelzunc** [comment]
Yes, sorry didn't catch the e-mail. As @imod said there is already a plugin for the use case of this PR. Why do you want to add this feature in the bitbucket-plugin as well?

**Comment by lkokhreidze** [comment]
There are several reasons:
1. There was corresponding task for this https://issues.jenkins-ci.org/browse/JENKINS-29605
2. Bitbucket pull request builder plugin doesn't support mercurial atm.

**Comment by imod** [comment]
@lkokhreidze I don't think these are valid reasons to integrate it into this plugin - I think both should be fixed in the pull request builder plugin.
As a user of the bitbucket-plugin myself, I would not expect pull requests suddenly to trigger a build after updating this plugin. The separation of the two plugins is also consistent with the two plugins for GitHub.

**Comment by fbelzunc** [comment]
> I don't think these are valid reasons to integrate it into this plugin - I think both should be fixed in the pull request builder plugin.
As a user of the bitbucket-plugin myself, I would not expect pull requests suddenly to trigger a build after updating this plugin. The separation of the two plugins is also consistent with the two plugins for GitHub.

:+1:  I think the bitbucket pull request plugin can be integrated with  mercurial in a similar way this one was. There is a pull request on this plugin if you would like to mimic what was done here.

**Comment by kesavkolla** [comment]
The fundamental difference between this plugin vs Bitbucket pull request builder is push vs pull.

Typically we don't want to setup a polling cron scheduler to check whether a PR is merged or not.  Since bitbucket already has ability to invoke webhooks it's much better approach to listen on multiple different events.

I've a requirement that we need to trigger build when a pull request is merged on a specific branch.  Currently there is no plugin that supports this.  Even pull request builder also doesn't handle the case of triggering build after PR is merged.

I think there is a validity in supporting multiple types of events from bitbucket.  Instead of hard coding the list of events these should be configurable.  So users can select what type of events that they want the build to trigger.

**Comment by alok15ee** [comment]
can I use groovy to enable the trigger inside a job ?

**Comment by TalAntR** [comment]
Definitly I'd like to have this feature too. Why I should few plugins to work with Bitbucket if an issue might be done with one plugin.

**Comment by sazo** [comment]
If peoples cant wait for this to get merged - i completed the pull-reqeust created feature.

OBS: The repo will only exist until this PR is merged.

https://github.com/sazo/bitbucket-plugin

**Comment by fbelzunc** [comment]
I will review again, but I am afraid there are still a lot of things wrong here. It might work for small size jenkins instances but on big environments this produces a lot of issues.

IIRC the way it works with this PR, all the bitbucket jobs will be now triggered as long as the repo is used - no check for the branch.

**Comment by redthor** [comment]
I think I am re-iterating @kesavkolla here https://github.com/jenkinsci/bitbucket-plugin/pull/25#issuecomment-206586742 but I don't think the [BitBucket Pull Request Builder](https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+pullrequest+builder+plugin) plugin is the right place for this feature. That plugin looks at PRs and checks them. We need a plugin that gets a Jenkins job going when a PR is merged.

There are now 90 forks (https://github.com/jenkinsci/bitbucket-plugin/network/members) of this repo and a lot of them look like they have forked just to add this feature, e.g

* https://github.com/jenkinsci/bitbucket-plugin/pull/32
* https://github.com/hopkins/bitbucket-plugin/commit/6269197ae4240b8443608a2ae632587ab6993ae7

For reference here is the closed JIRA ticket: https://issues.jenkins-ci.org/browse/JENKINS-29605

Can we please get an update to allow other Bitbucket events to trigger the plugin?

**Comment by redthor** [comment]
Hi @fbelzunc 

I read the documentation for the `Bitbucket Branch Source Plugin` and it talks about building from a branch?

I need our Jenkins Job to build from `master` when the `pullrequest:fulfilled` bitbucket event is submitted to Jenkins from the webhook. 

Can you confirm that the `Bitbucket Branch Source Plugin` will do that? I will give it a try if so.

thanks

**Comment by fbelzunc** [comment]
@redthor Yes, it is supported. See the source code:

* https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/b275d4ce6c5348cf2b35f39701987a1202695502/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEvent.java

**Comment by tzachs** [comment]
Closing this one as the plugin base version was updated to Jenkins base version 2.204.1
I'd be happy to discuss this if needed

**Pull request closed without merging**
