### PR TITLE
[REVERT JENKINS-30985] Trigger only one build per same scm

### PR DESCRIPTION
**Pull request by fbelzunc**
Revert #20 since JENKINS-29326 was fixed by @abayer in [jenkinsci/workflow-plugin/pull/271](https://github.com/jenkinsci/workflow-plugin/pull/271) and [git-plugin/pull/372](https://github.com/jenkinsci/git-plugin/pull/372)

@reviewbybees 

CC @jglick since I know you really want to revert this change ;-)

### CODE REVIEW

**Comment by jglick** [comment]
Did you manage to reproduce the original problem with this reversion in place, then confirm that it was fixed when you update to snapshot version of the Git and Workflow plugins?

**Comment by oleg-nenashev** [comment]
The PR is not mergeable.
If it is a bug in workflow, I don't understand why it has been fixed here. If it's a more generic bug affecting other plugins (E.g. MultipleSCM, Build Pipeline), I don't understand why it's being reverted now

**Comment by tzachs** [comment]
@fbelzunc this seems like an old PR that was already solved. Am I right? If so, can i close this one?

**Comment by tzachs** [comment]
Closing as this is an old case that was probably resolved

**Pull request closed without merging**
