### PR TITLE
support for new bitbucket webhooks with tests

### PR DESCRIPTION
**Pull request by dtao**
This PR introduces the same change as #16, but with some refactoring + unit tests.

### CODE REVIEW

**Comment by bskart** [comment]
Would be great to see this merged and released, we are currently trying to setup Jenkins-Integration on our Bitbucket-hosted repositories, including integration for pullrequests and are waiting for this fix to be integrated.

If there is anything I can do to help, just ask.

**Comment by smazurov** [comment]
likewise, perhaps for now we can get a custom `.hpi`?

**Comment by fbelzunc** [comment]
Hello, I will be happy to review the pull request, merge and produce a new release but I will need that you  update the pull-request as it looks like there are some conflicts.

You said:

> This PR introduces the same change as #16, but with some refactoring + unit tests.

Can we then close #16 then?

**Comment by sebastian301082-KAM** [comment]
Merge conflicts!

**Comment by dtao** [comment]
@fbelzunc @sebastian301082-KAM Yes there are conflicts, as this PR duplicates what was already done in #15 (which has already been merged).

My *recommendation* is that you revert the merge of #15 because I believe this PR contains a more desirable solution (it does not break existing integration with Bitbucket's old POST service, which still exists). If you agree with me, I'm happy to include the revert as part of this PR to eliminate the conflicts. Do you want me to take that approach?

@fbelzunc As for choosing between this and #16, it's up to you. I created both to give you the choice between a simpler change *without* tests and a more substantial change *with* tests. If you do end up merging this one, then yes, you can close #16.

**Comment by sstriano** [comment]
So does this plugin only support Git? Or does it also support Mercurial?

**Comment by dtao** [comment]
@sstriano It appears to only support Git. But that was already the case. I might look into adding Hg support in a separate PR.

**Comment by sstriano** [comment]
@dtao That would be awesome!! I have no idea how to do it otherwise I would. Is it an easy change?

**Comment by fbelzunc** [comment]
@dtao 

> If you agree with me, I'm happy to include the revert as part of this PR to eliminate the conflicts. Do you want me to take that approach?

This will be great! Please, do it and I will review and merge.

**Comment by dtao** [comment]
@fbelzunc All right, I've updated this PR (via `push -f` for a relatively clean commit history) w/ a revert of #15. Take a look and let me know what you think.

It would be great to get a new release out there for users who'd like to use this plugin w/ Bitbucket's new webhooks.

**Comment by fbelzunc** [comment]
@dtao Thank you very much!

**Comment by fbelzunc** [comment]
@domi Can you release, please? I have some problems releasing.

I will update the docs of the plugin once you do this - if you can ;-)

**Comment by dtao** [comment]
@fbelzunc @domi Let me know if there's anything I can do to help with the release.

**Comment by AmundsenJunior** [comment]
Thank you for making this very timely update to this plugin! My organization is in the middle of integrating Bitbucket, and this plugin would be a crucial part of our CI process.

Does anyone know by when the newest release of this plugin will be available through Jenkins plugins? https://wiki.jenkins-ci.org/display/JENKINS/BitBucket+Plugin still shows 1.1.0 as the latest release.

Apologies if this is an off-topic comment on this pull request thread.

Thanks

**Comment by fbelzunc** [comment]
@AmundsenJunior `1.1.1` should be already available in the Update Center. We released this morning CEST.

Tomorrow, I will upgrade https://wiki.jenkins-ci.org/display/JENKINS/BitBucket+Plugin

**Comment by AmundsenJunior** [comment]
@fbelzunc Ah, sorry for my confusion - I hadn't looked directly in Update Center, only at the wiki. Thanks, again!

**Comment by spacediver** [comment]
Thanks for the fix. Right at the moment http://updates.jenkins-ci.org/update-center.json shows 1.1.0, is this correct place I check? Clicking "check now" from inside Jenkins does not show up anythin newer either. Thanks!

**Comment by 4kochi** [comment]
Seems like the bitbucket api has changed again. I am using v1.1.2 of the plugin and Bitbucket v4.1.0
The Builds are not triggered in Jenkins and this is the error message:

```
Nov 26, 2015 12:27:35 PM INFORMATION com.cloudbees.jenkins.plugins.BitbucketPayloadProcessor processPayload
Processing old POST service payload

Received commit hook notification for {"slug":"demo","id":1,"name":"demo","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"DDD","id":1,"name":"Demo Project","public":false,"type":"NORMAL"},"public":false}
Nov 26, 2015 12:27:35 PM WARNUNG org.eclipse.jetty.util.log.JavaUtilLog warn
Error while serving http://192.168.20.29:8080/bitbucket-hook/
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$2.dispatch(MetaClass.java:165)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:366)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.sf.json.JSONException: JSONObject["user"] not found.
	at net.sf.json.JSONObject.getString(JSONObject.java:2040)
	at com.cloudbees.jenkins.plugins.BitbucketPayloadProcessor.processPostServicePayload(BitbucketPayloadProcessor.java:87)
	at com.cloudbees.jenkins.plugins.BitbucketPayloadProcessor.processPayload(BitbucketPayloadProcessor.java:29)
	at com.cloudbees.jenkins.plugins.BitbucketHookReceiver.doIndex(BitbucketHookReceiver.java:51)
	... 58 more
```

I have checked the data which is send from Bitbucket to Jenkins. Here is the header:

```
headers: 
   { 'content-type': 'application/json',
     'user-agent': 'Bitbucket 4.1.0',
     'x-atlassian-token': 'no-check',
     'content-encoding': 'UTF-8',
     accept: 'application/json',
     'content-length': '1585',
     host: '192.168.20.29:3000',
     connection: 'Keep-Alive',
     'accept-encoding': 'gzip,deflate' 
}
```

So the user-agent is different from that you use in your plugin to check for the new web hook api of Bitbucket.

**Comment by fbelzunc** [comment]
@4kochi I am currently taking a look at this.

**Comment by kariudo** [comment]
> It appears to only support Git. But that was already the case. I might look into adding Hg support in a separate PR.

@dtao Any movement on this being fixed for Mercurial? I'm still seeing this issue with our hg repos.

**Pull request merged**
