### PR TITLE
New Branch: Scan multibranch pipeline log

### PR DESCRIPTION
**Pull request by ca-stefan-cordes**
The
```
 triggers{
    bitbucketPush()
  }
```
is useful for standalone jenkinsfile projects and single branches of a multibranch project,
but when having a
* Multibranch Project

and pushing a new branch, the BitBucket WebTrigger is sending a push, but the
BitbucketJobProbe is checking for the update of "Job.class" only.

The "Scan Multibranch Pipeline Log" is not triggered (to find the new branch).
Workaround is to klick on "Scan Multibranch Pipeline Now" each time a new branch in created.

As this happens often when using git flow on that project I fixed the detection to search for all
"SCMSourceOwner.class" als well (which includes MultiBranchProject.class) where the URL is matching the configured one and then invoke "onSCMSourceUpdated".

As "SCMTriggerItem" has an SCM directly inside and the SCMSourceOwner just has a SCMSource I refactored the 2 "match" blocks to a method detecting the match based on the URIish.
(that's why it looks like to be more changes, but the block itself is unchanged)

### CODE REVIEW

**Comment by tomasz-lagodzinski-ynd** [comment]
Hi @fbelzunc, you you look at this PR? Seems to be fixing current issues with new branch detection.

**Comment by miikeat** [comment]
In the meantime just use this Jenkins Plugin in addition: https://plugins.jenkins.io/multibranch-scan-webhook-trigger/

**Comment by tzachs** [comment]
@ca-stefan-cordes I'm sorry but the code base has changed due to update to version 2.204.1.
Is this PR still needed? If so, any chance to fork from the new code base and write the code there?

**Comment by ca-stefan-cordes** [comment]
Yes, still needed.
I resetted to master and picked my "checking SCMSourceOwners/multiBranchProjects" change.

(scmSourceOwner.onSCMSourceUpdated is deprecated in the meanwhile but it is not clear for me whats the best way to trigger
 jenkins.plugins.git.GitSCMSource.ListenerImpl and/or hudson.plugins.mercurial.MercurialStatus - looks like several matching methods can be removed from BitbucketJobProbe. And so I took the deprecated method)

**Comment by tzachs** [comment]
@ca-stefan-cordes I see there are failures on windows agent. Can you please check it?

**Comment by ca-stefan-cordes** [comment]
```
[2020-08-30T17:33:26.147Z] [INFO] BUILD SUCCESS

[2020-08-30T17:33:26.147Z] [INFO] ------------------------------------------------------------------------

[2020-08-30T17:33:26.147Z] [INFO] Total time:  03:07 min

[2020-08-30T17:33:26.147Z] [INFO] Finished at: 2020-08-30T17:33:25Z

[2020-08-30T17:33:26.147Z] [INFO] ------------------------------------------------------------------------
```

But Sonar failed:
`[2020-08-30T17:42:57.823Z] EC2 (aws) - Windows 2019 (i-02af6be8a34858876) was marked offline: Connection was broken: java.io.EOFException`

**Comment by ca-stefan-cordes** [comment]
I merged the master which triggered a new build an now all checks have passed.

**Comment by tzachs** [comment]
Thanks @ca-stefan-cordes , I'll try to merge it ASAP 😃

**Comment by tzachs** [comment]
@ca-stefan-cordes merged and should be available in v1.1.24

**Pull request merged**
