### PR TITLE
Migrate bitbucket plugin documentation from Wiki to Github

### PR DESCRIPTION
**Pull request by nlk35**
I would like to migrate bitbucket plugin documentation from Wiki to Github. See https://www.jenkins.io/blog/2019/10/21/plugin-docs-on-github/

### CODE REVIEW

**Comment by fbelzunc** [comment]
It looks good to me - I am going to merge. 

However, considering moving from this plugin to https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin , which is the one which is really being maintained.

**Comment by daniel-beck** [comment]
Did this plugin have release documentation in https://github.com/jenkinsci/bitbucket-plugin/releases ? Asking because of the badge.

If so, I guess it was wiped when the last three years of master were rewritten in https://github.com/jenkinsci/bitbucket-plugin/pull/67#event-3600538623 ? Can we restore that somehow?

**Comment by tzachs** [comment]
@daniel-beck you mean this page https://plugins.jenkins.io/bitbucket/?

**Comment by daniel-beck** [comment]
I'm asking about 
Screenshot
which was added in this PR.

Makes little sense to add something like that if that's the output, so I'm wondering whether we lost data.

**Comment by tzachs** [comment]
@daniel-beck the re-write of history was done to change the author of my commits and only my commits have changed!
From https://github.com/jenkinsci/bitbucket-plugin/commits/master It looks like nothing was changed previous to what I have done (see attachment below)

I might be missing something here something and I'd be happy to understand what but I can't seem to see any difference in master prior to me changing the author in my commits only

image

**Comment by tzachs** [comment]
@nlk35 if I've destroyed something you have done, than first I'm sorry and 2nd I'd be happy to restore it if you can tell me how.

**Comment by daniel-beck** [comment]
@tzachs 

> It looks like nothing was changed previous to what I have done (see attachment below) meaning PR 72 is still merged in full in master

You're wrong. Superficially it looks like it, but all commits since 2017 were changed. That's why https://github.com/jenkinsci/bitbucket-plugin/pull/67 looks like such a mess, it lists dozens of commits and not just the one authored by my bot.

The oldest commit listed that is "added" in my PR is https://github.com/jenkinsci/bitbucket-plugin/commit/bf845bbfba232deac9c95533d40750b21805cf7f which you can see is not in `master`, but just in the PR branch. Instead, that commit is now on `master` as https://github.com/jenkinsci/bitbucket-plugin/commit/26c00f0ddd78164b57da0b837a4fb9302fa6bd57. All subsequent commits are also changed.

**Comment by tzachs** [comment]
@daniel-beck thank you very much for taking the time and showing me how to find the mistake, I appreciate it! (no kidding, I'm serious 😃 )
Again, sorry for the lost.
Is there a way to see if a tag is lost?

**Comment by daniel-beck** [comment]
@tzachs Do you know what you did, exactly? Perhaps you have console logs around?

All tags seem to exist, but at a glance they appear to match current master, rather than what they were before.

**Comment by tzachs** [comment]
@daniel-beck,
At first i've used the following

```
 git filter-branch --env-filter 'if [ "$GIT_AUTHOR_EMAIL" = "<MY WRONG MAIL>" ]; then
     GIT_AUTHOR_EMAIL=tzach.solomon@gmail.com;
     GIT_AUTHOR_NAME="tzachs";
     GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL;
     GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"; fi' -- --all
```
but that did not work, so i've used what is written at https://www.git-tower.com/learn/git/faq/change-author-name-email and https://tanimislamblog.wordpress.com/2019/11/05/how-to-use-git-filter-repo-to-change-inconvenient-emails/ which is

`git filter-repo --force --mailmap my-mailma`

**Comment by daniel-beck** [comment]
I see. Well, clearly there was nothing accidental about it.

Quoting from the first link:

> #### Editing Past Commits Rewrites History!
> 
> No matter how exactly we change the information of past commits, there's one thing to always keep in mind: if we do this, we are effectively **rewriting commit history**.
> This is nothing to take lightly: you will create new commit objects in this process, which can become a serious problem for your collaborators - because they might have already based new work on some of the original commits.
> Therefore, **think twice before you rewrite your commit history!**

**Comment by tzachs** [comment]
@daniel-beck this is the last time I'm going to say sorry about this.
Sorry. This was a mistake. I did not mean for this to happen.

Now, if you have something to add in terms of helping to fix the situation I'd be very much happy to assist.

Notice that this plugin was not maintained for a while and I took to myself to do it with the purpose of giving back (and of course my love of programming).

I hope your next comment will be with some positive elements to it and not reminding me the mistake (which I did without the intent of ruining everyones world)

Thanks

**Comment by daniel-beck** [comment]
I'm not sure how best to proceed here. If there hadn't been any new releases since the force push we'd just go back to the earlier state, but that's not what we have.

We can merge the old HEAD into the new one and then the history will _look_ messed up but it will at least be complete, even if very redundant.

The old, changed tags are either the larger problem, or lesser, depending on whether you expect the history to be correct for them or just the content.

I still don't know whether we lost metadata attached to releases/tags, which is the original reason I commented here.

**Comment by daniel-beck** [comment]
> We can merge the old HEAD into the new one and then the history will look messed up but it will at least be complete, even if very redundant.

And obviously this will restore whatever data you meant to redact, so perhaps not something you're willing to do.

**Comment by tzachs** [comment]
I understand your view on losing the history but my first and primary concert is if the functionality of the plugin has been damaged. From I've tested it wasn't.
I do not want to merge HEAD back as I want to move on forward from this point.

As you've noticed, I'm putting an effort to merge/close all the PR so we could have a clean slate.

As for the documentation, I hope I'll get to this ASAP in order to fix it.

**Comment by daniel-beck** [comment]
> but my first and primary concert is if the functionality of the plugin has been damaged. From I've tested it wasn't.

Content is unchanged, this was never the concern. I'm sorry if this wasn't clear. The problem is around commit metadata (like potential loss of GitHub release metadata for tags), and problems resulting from that (like contributors with existing forks having problems submitting new pull requests without some extra effort).

Obviously, if you don't consider those important, there's nothing to be done here (except perhaps removing the now unnecessary badge from the readme).

**Comment by tzachs** [comment]
I consider the metadata (and giving created to PR submitter) to most important but the reality now is that I can't do anything about it.

As for the badge, I'll try to see how to fix it.

**Pull request merged**
