### PR TITLE
Adding support for destination branch filtering and more actions

### PR DESCRIPTION
**Pull request by douglasmiller**
This pull request expands on the changes made by @Shyri in #28 and #29.

I have added the ability to filter by the pull request destination branch. This functionality was based on the Git Plugin's branch filtering wildcards \* and **.

I have also added support for Updated and Merged pull request hooks from bitbucket.

I know that @jrtheinert mentioned a desire to expand on @Shyri's original PR. I hope that these additions can help with that.

I should provide a disclaimer that I haven't written much Java lately. Please let me know if there is anything that I should update.

### CODE REVIEW

**Comment by kgrubb** [comment]
Just a small heads up, it looks like bitbucket's "merge" trigger uses `pullrequest:fulfilled` instead of `pullrequest:merged`.

**Comment by douglasmiller** [comment]
Thanks for the heads up, @kgrubb.

@fbelzunc, I've found the time to pick this back up. I added the MIT license and updated the DSL. I'm certain that I am approaching the second `PullRequestTriggerFilter` parameter incorrectly.  I'm also not certain how to go about testing the DSL code.

Could you provide any guidance on that?

**Comment by redthor** [comment]
Hi @douglasmiller - thanks for this.

Having the Bitbucket plugin run when a PR is merged (`pullrequest:fulfilled`) into `master` is exactly what we need. 

Do you know how we could use your fork with our Jenkins installation? Will I need to get the code, compile it, and then install?

**Comment by douglasmiller** [comment]
Closing because I'm fairly certain that it will not ever get merged and I'm tired of seeing it in my open PRs list

**Pull request closed without merging**
