### PR TITLE
Compatibility with post-webhooks-for-bitbucket 1.6.3, ssh/http improvement

### PR DESCRIPTION
**Pull request by vzickner**
* Make it compatible with JSON produced by post-webhooks-for-bitbucket
  1.6.3 for Bitbucket Server (might be related to new bitbucket server version)
* Create compatibility in case BitBucket is deployed in case BitBucket
  has a context pass by comparing clone URLs

### CODE REVIEW

**Comment by krotte1** [comment]
I prefer the flexibility provided in https://github.com/jenkinsci/bitbucket-plugin/pull/58 over this set of changes

**Comment by tzachs** [comment]
@vzickner I'm sorry but the code base has changed due to upgrade to Jenkins version 2.204.1
Is this change still needed? If so, any chance you can fork from the new code base and write the code there?

**Comment by vzickner** [comment]
Hi @tzachs,
thanks for checking. I don't know, we can close the PR for now. I will re-open another one in case needed.
Valentin

**Comment by tzachs** [comment]
Thanks @vzickner 🙏 :)

**Pull request closed without merging**
