### PR TITLE
Ignore payload processing for diagnostics:ping

### PR DESCRIPTION
**Pull request by tkrisztian95**
Fix plugin responses error for Bitbucket Webhooks when Test Connection.
When using a Post Webhook "Test Connection" button on push with Bitbucket Server 6.1.3 (self-hosted). I am using Bitbucket Plugin 1.1.10.  (on Jenkins 2.187)
Error:
`at net.sf.json.JSONObject.getString(JSONObject.java:2040)
	at com.cloudbees.jenkins.plugins.BitbucketPayloadProcessor.processPostServicePayload(BitbucketPayloadProcessor.java:143)
	at com.cloudbees.jenkins.plugins.BitbucketPayloadProcessor.processPayload(BitbucketPayloadProcessor.java:38)
	at com.cloudbees.jenkins.plugins.BitbucketHookReceiver.doIndex(BitbucketHookReceiver.java:54)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)`

### CODE REVIEW

**Comment by krotte1** [comment]
This would be a good fix to have.

**Comment by tzachs** [comment]
@tkrisztian95 is this still relevant? the code base has changed due to update of the plugin to version 2.204.1

**Comment by tkrisztian95** [comment]
@tzachs Good question. Maybe it is, besides it was a while when I was working with the plugin. I'm pretty sure if a diagnostics message comes from Bitbucket we should not pass it to further processing. This caused problems in our setup due to the plugin tried to parse out info from the ping message but instead ignoring it.

**Comment by tzachs** [comment]
@tkrisztian95 thanks for getting back to me. I appreciate it a lot :)
 I'll see how I can merge the code or I'll just copy the commit content and write this PR and you as the contributor. 
Is that OK?

**Comment by tzachs** [comment]
@tkrisztian95 ?

**Comment by tkrisztian95** [comment]
@tzachs Sorry for the late reply. Sure, it ok!

**Comment by tzachs** [comment]
@tkrisztian95 I've manually added the code in 1.1.23, thanks for this PR 😃

**Pull request closed without merging**
