### PR TITLE
[JENKINS-41635] Allow BITBUCKET_PAYLOAD to work in pipeline jobs

### PR DESCRIPTION
**Pull request by fbelzunc**
https://issues.jenkins-ci.org/browse/JENKINS-41635

### CODE REVIEW

**Comment by Firefishy** [comment]
Would love to see this merged. We have been caught out by https://issues.jenkins-ci.org/browse/JENKINS-41635

**Comment by fbelzunc** [comment]
I will try to do this tomorrow.

**Comment by tzachs** [comment]
@Firefishy I think to close this PR since it is not compiling and also I've upgrade the plug-in to use Jenkins 2.204.1 as base.

WDYT?

**Comment by Firefishy** [comment]
@tzachs I no longer have a requirement for this, but I think the minimal change required is just a few lines of code.

@cyberbliss may remember more from when we looked at this.

**Comment by cyberbliss** [comment]
@tzachs @Firefishy I've no requirement for this anymore, either. FYI the reason it was important at the time is that BITBUCKET_PAYLOAD contains some useful details about the PR/merge commit which is triggering the pipeline. Details which aren't easily available otherwise

**Comment by tzachs** [comment]
@Firefishy @cyberbliss thank you for the quick response 😃 
If this issue will rise up again we'll see how to handle it

**Comment by StefanIGit** [comment]
Hi, I'm not sure if it is the same issue, abut sound like it,
We migrate to Bitbucket Cloud from Server and as far as I can tell this plugin is the only way to trigger our Jenkins jobs.
we have a mix of freestyle and pipeline jobs, I can parse the BITBUCKET_PAYLOAD in the freestyle w/o a problem but I do not have the variable in the pipeline jobs.

Any idea how I can solve this?

**Comment by tzachs** [comment]
@StefanIGit thanks for commenting.
Is it OK we'll continue this thread in the original https://issues.jenkins-ci.org/browse/JENKINS-41635?

**Comment by vvchistyakov** [comment]
Hi there. it looks like I also met the problem of getting BITBUCKET_PAYLOAD inside a pipeline job.
We use the BB Cloud and get a webhook payload via Generic Webhook Trigger instead. Probably, you could implement getting the payload in the BB plugin.

**Comment by tzachs** [comment]
@vvchistyakov I've fixed it in https://issues.jenkins.io/browse/JENKINS-41635 but I'm unable to release it yet. Please follow https://issues.jenkins.io/browse/JENKINS-41635 for more updates

**Comment by tzachs** [comment]
Fixed in https://github.com/jenkinsci/bitbucket-plugin/releases/tag/223.vd12f2bca5430

**Comment by vvchistyakov** [comment]
@tzachs thank you. I appreciate it. I check it after upgrading our Jenkins installations.
Will give feedback later.

**Pull request closed without merging**
