### PR TITLE
Show what project is triggered not just branch

### PR DESCRIPTION
**Pull request by ca-stefan-cordes**
On Info Level the log lines on a multibranch project that are produced are

```
Dez 08, 2019 1:54:00 PM **INFO** com.cloudbees.jenkins.plugins.BitbucketJobProbe triggerMatchingJobs
Triggering BitBucket job develop
```

which is not really helpful as "job.getName()" is just the branch name.
Like on the fine level log statement above the "job.getFullDisplayName()" should be printed:
```
Dez 08, 2019 1:54:00 PM **FINE** com.cloudbees.jenkins.plugins.BitbucketJobProbe
Considering to poke test-multibranch » develop
```
which is more helpful.

### CODE REVIEW

**Comment by tzachs** [comment]
@ca-stefan-cordes since the plugin Jenkins base version was updated to 2.204.1, the code was changed.
Can you please re-fork this one and make the changes you need? 
This PR should be closed unless you are really against it.

**Comment by tzachs** [comment]
@ca-stefan-cordes ?

**Comment by ca-stefan-cordes** [comment]
Hi @tzachs,
I am still interested in having a useful log (getFullDisplayName instead of getName),
update will follow...

**Comment by ca-stefan-cordes** [comment]
Hi @tzachs,
I tried to re-use this pull-request via force pushing the re-setted brach to my repo, but github closed this PR.
So I created a new one against current master: https://github.com/jenkinsci/bitbucket-plugin/pull/78

**Comment by tzachs** [comment]
Hi @ca-stefan-cordes ,

Thanks for opening a new PR. sorry for the hassle

**Pull request closed without merging**
