### PR TITLE
JENKINS-28877

### PR DESCRIPTION
**Pull request by kzusy**
The BitBucket event payload changed so made some modifications accordingly.  Instead of supplying a string for the "user", an "actor" object is included, which you can grab the username from.  Instead of "canon_url" and "absolute_url", the "repository" object has a "links" object that you can grab the repo url from.  "scm" is no longer included.  It's possible to get "scm" by making an api request, but if the repo is private, it would require authentication as well.  There are additional checks in processPayload() so I felt safe removing the check for now

### CODE REVIEW

**Comment by lordkada** [comment]
I've tested your PL in my own configuration (BitBucket with private repo and Jenkins 1.554.3) and it worked... great!

In addition, I'd suggest to update the reference json (payload) in the BitBucketHookReceiver.java (62 and following)

**Comment by kzusy** [comment]
Thanks @lordkada.  Updated the reference json as suggested

**Comment by JonnyBGod** [comment]
+1

**Comment by bitonator** [comment]
Is anyone merging to master? I'm currently setting up a build server, and I'm stuck at this point

**Comment by lordkada** [comment]
@bitonator I've compiled myself... if you need now I can share my build: https://dl.dropboxusercontent.com/u/15982375/bitbucket.jpi

**Comment by bitonator** [comment]
+1 @lordkada works great

**Comment by sebastian301082-KAM** [comment]
We've same issue. It would be good to get this PR merged soon. Thanks

**Comment by dtao** [comment]
Gah! You beat me to it by a few hours! See #16 and #17.

One thing I will say is that in this PR you are *removing* support for the old POST service. The PR I just created instead *adds* support without breaking backwards compatibility by checking the request for the "Bitbucket-Webhooks/2.0" header and using either the new logic or the old logic accordingly.

It *might* be worth considering reverting this and merging my PR.

Regardless, nice work!

**Comment by lordkada** [comment]
Any plan to release a new version of this plugin?

Btw I hadn't time to test the #17 from @dtao and I don't know if that scenario really could occur, but it sounds reasonable...

**Comment by dtao** [comment]
@lordkada The scenario could definitely occur. We (Bitbucket) have not yet removed the old POST service, so integrations using the old payload still exist and are still being created. If the plugin is updated with this change, it will be necessary to inform users that they need to install an older version to integrate with the POST service.

**Comment by lordkada** [comment]
@dtao thanks for the explanation ;-)

**Pull request merged**
