### PR TITLE
Implemented pull-request created feature

### PR DESCRIPTION
**Pull request by sazo**
First of all - B-E-A-tifull coding from @fbelzunc and @Shyri - very easy to extend and develop on.

I finished implementing the trigger for on pull request create event.

Hope you like it.

I know the comment in README is not for you repo - is for mine until the development is done here.

### CODE REVIEW

**Comment by ip1981** [comment]
I like it :)

**Comment by jeremychauvet** [comment]
🙏

**Comment by tzachs** [comment]
@sazo is this still relevant? I'm asking cause the code base has changed so I can't merge this into master

**Comment by sazo** [comment]
I don't know :) it's 3 year old code so it woot surprise me if it works. We have switched to bitbucket-source-branch plugin supports everything.

**Comment by tzachs** [comment]
Cool ,thanks for replying @sazo :) I appreciate it! :)

**Pull request closed without merging**
