### PR TITLE
Added support for --skip-ci, [ci skip] and [skip ci]

### PR DESCRIPTION
**Pull request by gabotz**
Basically added support for "--skip-ci", "[ci skip]" and "[skip ci]" in commit messages to skip triggering a job build

### CODE REVIEW

**Comment by gabotz** [comment]
I just tested in my jenkins and the payload does NOT contain commit information

**Comment by gabotz** [comment]
Updated to Bitbucket's payload model

**Comment by Karnich** [comment]
can we do something about this?

**Comment by tzachs** [comment]
Hi @gabotz ,

Can you please explain to me why do we need this feature? I'm probably missing out something here.

**Comment by tzachs** [comment]
Closed as there is no answer

**Pull request closed without merging**
